list:
    path: /exigibilidades
    controller: App\Controller\Web\ExigibilidadeWebController::list
    methods: ['GET']

create:
    path: /exigibilidades/criar
    controller: App\Controller\Web\ExigibilidadeWebController::create
    methods: ['GET', 'POST']

export_xml:
    path: /exigibilidade/export/xml
    controller: App\Controller\Web\ExigibilidadeWebController::exportXml
    methods: ['GET']

edit:
    path: /exigibilidades/{id}/editar
    controller: App\Controller\Web\ExigibilidadeWebController::edit
    methods: ['GET', 'POST']
